### ISSUE TITLE
Latest release RBXM is built incorrectly

### ISSUE THREAD

**Issue by evaera** [vocksel/import#6]
The [latest release](https://github.com/vocksel/import/releases/tag/v1.1.0) `import.rbxm` asset is missing the `lib` folder and most of the library.

![image](https://user-images.githubusercontent.com/2489210/97791738-17a5d180-1bac-11eb-968b-e400a2acd4ef.png)

**Comment by WorldPosition** [comment]
Just noticed this as well.

**Comment by vocksel** [comment]
Rebuilt the binary, lemme know if that works
